const ourteam = [
  {
    name: "Dr K Vishnuvardhan",
    image: require("../assets/OurTeam/facultyCoordinator..jpg"),
    position: "ASP Sr.G/ CIVIL",
    description: "",
    year: "2023",
  },
  {
    name: "K. Vishnu Promoth",
    image: require("../assets/OurTeam/promoth.jpg"),
    position: "President",
    description: "",
    year: "2023",
  },
  {
    name: "K. Lakshanaa",
    image: require("../assets/OurTeam/lakshana_secretary.jpg"),
    position: "Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "E. Santhosh",
    image: require("../assets/OurTeam/santosh_trasurer.jpg"),
    position: "Treasurer",
    description: "",
    year: "2023",
  },
  {
    name: "A.V. Dharshan",
    image: require("../assets/OurTeam/dharshan.jpg"),
    position: "Vice-President",
    description: "",
    year: "2023",
  },
  {
    name: "A. Vingeshwara",
    image: require("../assets/OurTeam/ADDITIONAL SECRETARY _VIGNESHWARAN.jpg"),
    position: "Additional-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "S. Abinaya",
    image: require("../assets/OurTeam/Additional Treasurer_Abinaya S_ECE.jpg"),
    position: "Additional-Treasurer",
    description: "",
    year: "2023",
  },
  {
    name: "R. Srikanth",
    image: require("../assets/OurTeam/srikanth_new.webp"),
    position: "Joint-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "S. Srinath",
    image: require("../assets/OurTeam/srinath.jpg"),
    position: "Joint-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "S. Sagana",
    image: require("../assets/OurTeam/SAGANA S - joint secretary -MBA.jpg"),
    position: "Joint-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "R. Nishanth",
    image: require("../assets/OurTeam/Joint secretary Nishanth.jpg"),
    position: "Joint-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "Y. Subhavarsha",
    image: require("../assets/OurTeam/subhavarsha.jpeg"),
    position: "Joint-Secretary",
    description: "",
    year: "2023",
  },
  {
    name: "G. Rithanya",
    image: require("../assets/OurTeam/RITHANYA_G_PROJECT_HEAD.jpg"),
    position: "Project Head",
    description: "",
    year: "2023",
  },
  {
    name: "D. Harryarajan",
    image: require("../assets/OurTeam/harry.jpg"),
    position: "Project Head",
    description: "",
    year: "2023",
  },
  {
    name: "A. Sam Ronald",
    image: require("../assets/OurTeam/sargent-at-arms_sam ronald_mech.jpg"),
    position: "Sargent-at-arms",
    description: "",
    year: "2023",
  },
  {
    name: "S. Subhika",
    image: require("../assets/OurTeam/subhika.jpg"),
    position: "Sargent-at-arms",
    description: "",
    year: "2023",
  },
  {
    name: "S. Yuvaraj",
    image: require("../assets/OurTeam/sargent-at-arms_yuvaraj_CHEM.jpg"),
    position: "Sargent-at-arms",
    description: "",
    year: "2023",
  },
  {
    name: "M. Sri Aksharee",
    image: require("../assets/OurTeam/Director of community service_Sri Aksharee_MCA.jpg"), 
    position: "Director of Community Service",
    description: "",
    year: "2023",
  },
  {
    name: "R. Vishnu",
    image: require("../assets/OurTeam/Director of Community Service_VISHNU R D_IT.jpg"),
    position: "Director of Community Service",
    description: "",
    year: "2023",
  },
  {
    name: "P. Sarath",
    image: require("../assets/OurTeam/Director of community service_SARATH P.jpg"),
    position: "Director of Community Service",
    description: "",
    year: "2023",
  },
  {
    name: "S.R. Kharnika",
    image: require("../assets/OurTeam/Director of public relationship_Kharnika_EIE (1).jpg"),
    position: "Director of Public Relationship",
    description: "",
    year: "2023",
  },

  {
    name: "P. Santhosh",
    image: require("../assets/OurTeam/Director of international service_Santhosh_MTS_.jpg"), 
    position: "Director of International Service",
    description: "",
    year: "2023",
  },
  {
    name: "R.C. Vishnurajha",
    image: require("../assets/OurTeam/Vishnurajha.jpg"),
    position: "Director of International Service",
    description: "",
    year: "2023",
  },
  {
    name: "Manikandan",
    image: require("../assets/OurTeam/Director of International Service_MANIKANDAN R_AUTO.jpg"), 
    position: "Director of International Service",
    description: "",
    year: "2023",
  },
  {
    name: "M. Kiruthika",
    image: require("../assets/OurTeam/Director of professional service_Kiruthika.R_CSE (1).jpg"), 
    position: "Director of Professional Service",
    description: "",
    year: "2023",
  },
  {
    name: "K.P. Karnika",
    image: require("../assets/OurTeam/Director of youth service_Karnika_EEE.jpg"),
    position: "Director of Youth Service",
    description: "",
    year: "2023",
  },
  {
    name: "B. Sabari",
    image: require("../assets/OurTeam/Documentation_Team_Sabari_MECH.jpg"),
    position: "Director of Documentation",
    description: "",
    year: "2023",
  },
  {
    name: "A. Sundhar",
    image: require("../assets/OurTeam/ADDITIONAL SECRETARY _VIGNESHWARAN.jpg"), //photo should be change
    position: "Director of Photography",
    description: "",
    year: "2023",
  },
  {
    name: "G. Hareesh",
    image: require("../assets/OurTeam/Director of club service_Hareesh.G_EIE.jpg"),   
    position: "Director of Club Service",
    description: "",
    year: "2023",
  },
  {
    name: "G. Shyam Ganesh",
    image: require("../assets/OurTeam/shyam (1).jpg"), 
    position: "Media Team",
    description: "",
    year: "2023",
  },
  {
    name: "S. Ajay",
    image: require("../assets/OurTeam/ajay.jpg"),
    position: "Media Team",
    description: "",
    year: "2023",
  },
  {
    name: "R. Athithya",
    image: require("../assets/OurTeam/ajai.webp"), //photo should be change
    position: "Media Team",
    description: "",
    year: "2023",
  },

  
];

export default ourteam;

