export const G2k17 = [
    {
      id: 1,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 2,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 3,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 4,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 5,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 6,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Steve",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
  ];
  export const G2k18 = [
    {
      id: 1,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 2,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 3,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 4,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 5,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 6,
      quoute: "Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "S",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    }
  ];
  export const G2k19 = [
    {
      id: 1,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 2,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 3,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 4,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 5,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 6,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "St",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
  ];
  export const G2k20 = [
    {
      id: 1,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 2,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 3,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 4,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 5,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 6,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Ste",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
  ];
  export const G2k21 = [
    {
      id: 1,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 2,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 3,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 4,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 5,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
    {
      id: 6,
      quoute: "Calvin: Sometimes when I'm talking with others, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Hobbes: Probably so we can think twice.",
      author: "Stev",
      imageSrc:"https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sq-sample1.jpg",
      altText:"sq-sample1",
    },
  ];